site_name: fb-library
site_url: https://fb-library.readthedocs.io/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.path
    - toc.integrate
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 3
  - markdown_include.include:
      base_path: .
nav:
  - Overview: index.md
  - Developer’s Guide:
    - clickfit: click_fit.md
    - dovetail: dovetail.md
    - HexWall: hexwall.md
    - Point: point.md
    - twist_snap: twist_snap.md